name: py310_selenium_env
channels:
  - conda-forge

dependencies:
  - python=3.10.14                # https://pyreadiness.org/3.10
  - pip=24.0                      # https://pip.pypa.io/en/stable/news
  - pip:
    - selenium==4.25.0             # https://pypi.org/project/selenium/
    - openpyxl==3.2.0b1            # https://pypi.org/project/openpyxl/
    - python-dateutil==2.9.0.post0 # https://pypi.org/project/python-dateutil/